[package]
name = "etw"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.2.2"
[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Etw",
    "Win32_System_Threading",
    "Win32_System_Kernel",
    "Win32_System_Time"
]